### ISSUE TITLE
Allow ‘guest’ entries

### ISSUE THREAD

**Issue by ReactiveRaven** [Devographics/StateOfJS-legacy#212]
Clicking the link from the mailing list prompted me to enter a password to create an account.
Allowing ‘guest’ submission should reduce friction and allow collecting more results from a wider audience.

**Comment by fishsaidno** [comment]
Not sure how much spam / how many duplicates were received in previous years, but 
```
'Enter password' === 'Close tab'
```
SSO with GitHub might have been smoother.

**Comment by Airblader** [comment]
> ## Why do I need to create an account?
> We ask you to create an account in order to:
> * Avoid duplicate responses
> * Give you access to your data
> * Save your session as you go
> * Notify you when results are live

– https://survey.stateofjs.com/
